# This GitHub Actions workflow automates the process of building, pushing, and deploying a containerized web application to an 
# Azure Web App. It starts by checking out the repository code and setting up Docker Buildx. Then, it logs in to the Azure 
# Container Registry, builds and pushes the container image to the registry, and deploys the container image to the Azure Web App's 
# production slot.

# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - profstatsutd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://profstatsutd.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_dad78c03511a49a890d56e29b1d04379 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8ef8365db6a94ff0bbdca4fb5bff7308 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: profstatsutd.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dad78c03511a49a890d56e29b1d04379 }}/profstatsutd:${{ github.sha }}
        file: Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'profstatsutd'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_37720a23126a43768dde343a28641880 }}
        images: 'profstatsutd.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dad78c03511a49a890d56e29b1d04379 }}/profstatsutd:${{ github.sha }}'