name: Backend Testing

on:
  push:
    paths:
      - 'api/**'
      - 'db_setup/**'
      - 'raw_data/**'
  workflow_dispatch:

jobs:
  test_backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Run create_db.py
        run: python db_setup/create_db.py
        
      - name: Run test_db.py
        run: python db_setup/test_db.py  
        continue-on-error: false
    
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        working-directory: api
        run: go get .
      - name: Test with Go
        working-directory: api
        run: go test -v ./...
        continue-on-error: false
